
import static java.lang.Integer.parseInt;


public class InterfazUsuario extends javax.swing.JFrame {
    /**
     * Creates new form InterfazUsuario
     */
    
    ArbolBinario arbol = new ArbolBinario();

    public InterfazUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_id_libro = new javax.swing.JLabel();
        jTextField_id_libro = new javax.swing.JTextField();
        jLabel_nombre_libro = new javax.swing.JLabel();
        jTextField_nombre_libro = new javax.swing.JTextField();
        jTextField_publi_libro = new javax.swing.JTextField();
        jLabel_publi_libro = new javax.swing.JLabel();
        jButton_incl_libro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_repre_arbol = new javax.swing.JTextArea();
        jLabel_repre_arbol = new javax.swing.JLabel();
        jLabel_mensaje_arbol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Inclusión de libros");

        jLabel_id_libro.setText("ID del Libro");

        jLabel_nombre_libro.setText("Nombre del Libro");

        jLabel_publi_libro.setText("Año de Publicación");

        jButton_incl_libro.setText("Incluir Libro");
        jButton_incl_libro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_incl_libroMouseClicked(evt);
            }
        });

        jTextArea_repre_arbol.setColumns(20);
        jTextArea_repre_arbol.setRows(5);
        jScrollPane1.setViewportView(jTextArea_repre_arbol);

        jLabel_repre_arbol.setText("Representación del Árbol");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel_id_libro)
                            .addComponent(jTextField_id_libro)
                            .addComponent(jLabel_nombre_libro)
                            .addComponent(jTextField_nombre_libro, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jLabel_publi_libro)
                            .addComponent(jTextField_publi_libro, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jButton_incl_libro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_repre_arbol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_mensaje_arbol)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel_id_libro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_id_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_nombre_libro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_nombre_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_publi_libro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_publi_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_incl_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_repre_arbol)
                    .addComponent(jLabel_mensaje_arbol))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_incl_libroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_incl_libroMouseClicked
        jTextArea_repre_arbol.setEditable(false);

        int id = parseInt(jTextField_id_libro.getText());
        String nombre = jTextField_nombre_libro.getText();
        int anio_pub = parseInt(jTextField_publi_libro.getText());
        
        Libro nuevoLibro = new Libro(id, nombre, anio_pub);
        
        if (arbol.insertar(nuevoLibro)){
            jTextArea_repre_arbol.setText(arbol.imprimirArbol());
            jLabel_mensaje_arbol.setText("Libro insertado correctamente.");
        } else {
            jLabel_mensaje_arbol.setText("El ID del libro ya existe.");
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton_incl_libroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_incl_libro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_id_libro;
    private javax.swing.JLabel jLabel_mensaje_arbol;
    private javax.swing.JLabel jLabel_nombre_libro;
    private javax.swing.JLabel jLabel_publi_libro;
    private javax.swing.JLabel jLabel_repre_arbol;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_repre_arbol;
    private javax.swing.JTextField jTextField_id_libro;
    private javax.swing.JTextField jTextField_nombre_libro;
    private javax.swing.JTextField jTextField_publi_libro;
    // End of variables declaration//GEN-END:variables
}
